[package]
name = "sui-rosetta"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum = "0.5.13"
axum-macros = "0.2.3"
anyhow = { version = "1.0.58", features = ["backtrace"] }
tracing = "0.1.36"
serde = "1.0.143"
serde_json = "1.0.83"
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tokio = "1.20.1"
lazy_static = "1.4.0"
serde_with = "2.0.0"
itertools = "0.10.3"
signature = "1.6.0"
bcs = "0.1.3"

sui-sdk = { path = "../sui-sdk" }
sui-types = { path = "../sui-types" }

